### ISSUE TITLE
GPU inference

### ISSUE THREAD

**Issue by egorsmkv** [egorsmkv/whisper-optimized-intel#1]
```
python run_gpu.py "openai/whisper-medium" "whisper-medium-onnx-int4-inc" "ukrai
nian_speech.wav"
You are using a model of type whisper to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
2024-09-03 12:01:23.706029979 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 240 Memcpy nodes are added to the graph torch_jit for CUDAExecution
Provider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detai
l logs before this message.
2024-09-03 12:01:23.715706320 [W:onnxruntime:, session_state.cc:1166 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred exe
cution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-09-03 12:01:23.715724727 [W:onnxruntime:, session_state.cc:1168 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal bu
ild will show node assignments.
2024-09-03 12:01:24.926193861 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 385 Memcpy nodes are added to the graph torch_jit for CUDAExecution
Provider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detai
l logs before this message.
2024-09-03 12:01:24.938447946 [W:onnxruntime:, session_state.cc:1166 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred exe
cution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-09-03 12:01:24.938462400 [W:onnxruntime:, session_state.cc:1168 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal bu
ild will show node assignments.
2024-09-03 12:01:25.887376262 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 337 Memcpy nodes are added to the graph torch_jit for CUDAExecution
Provider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detai
l logs before this message.
2024-09-03 12:01:25.897504261 [W:onnxruntime:, session_state.cc:1166 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred exe
cution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-09-03 12:01:25.897517924 [W:onnxruntime:, session_state.cc:1168 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal bu
ild will show node assignments.
audio_data shape: (1, 246936)
/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/transformers/generation/utils.py:1850: UserWarning: You are calling .generate() with
the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience une
xpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_
ids.to('cuda') before running `.generate()`.
  warnings.warn(
/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/transformers/generation/utils.py:951: FutureWarning: You have explicitly specified `f
orced_decoder_ids`. This functionality has been deprecated and will throw an error in v4.40. Please remove the `forced_decoder_ids` argument in favour
 of `input_ids` or `decoder_input_ids` respectively.
  warnings.warn(
Traceback (most recent call last):
  File "/root/whisper-intel-optimized/run_gpu.py", line 44, in <module>
    generated_ids = model.generate(
                    ^^^^^^^^^^^^^^^
  File "/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/transformers/generation/utils.py", line 1989, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/transformers/generation/utils.py", line 2932, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/optimum/modeling_base.py", line 95, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/optimum/onnxruntime/modeling_seq2seq.py", line 1375, in forward
    decoder_outputs = model(
                      ^^^^^^
  File "/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/optimum/onnxruntime/base.py", line 85, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/optimum/onnxruntime/base.py", line 260, in forward
    known_output_shapes = self.compute_past_key_values_output_shapes(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/optimum/onnxruntime/base.py", line 194, in compute_past_key_values_output_shapes
    num_attention_heads = self.normalized_config.num_attention_heads
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/whisper-intel-optimized/.venv/lib/python3.12/site-packages/optimum/utils/normalized_config.py", line 69, in __getattr__
    raise AttributeError(f'Could not find the attribute named "{leaf_attr_name}" in the normalized config.')
AttributeError: Could not find the attribute named "num_attention_heads" in the normalized config.
```

**Comment by egorsmkv** [comment]
```
optimum-cli export onnx --device cuda --model openai/whisper-medium --task automatic-speech-recognition-with-past --framework pt --opset 17 --dtype fp16 --optimize O4  whisper-medium-with-past/

optimum-cli onnxruntime quantize --onnx_model whisper-medium-with-past/ --avx512 -o whisper-medium-with-past_onnx_quantized
```

**Comment by egorsmkv** [comment]
https://github.com/intel/intel-extension-for-transformers/tree/main/examples/huggingface/onnxruntime/speech-recognition/quantization
